default: &default_params
    dataroot: '../../data/dtd/'
    workers: 2 # number of data loading workers
    batchSize: 64 # input batch size
    imageSize: 516 # the height / width of the input image to network
    nz: 10 # depth of the latent z tensor
    nw: 4 # height and width of z tensor
    ntw: 160 # height and width of z tensor at test time
    ngf: 128
    ndf: 128
    niter: 25 # number of epochs to train for
    lr: 0.0002 # learning rate
    beta1: 0.5 # beta1 for adam
    cuda: True # enables cuda
    ngpu: 1 # number of GPUs to use
    netG: '' # path to netG (to continue training)
    netD: '' # path to netD (to continue training)
    outf: 'outputs/' # folder to output images and model checkpoints
    manualSeed: # manual seed
    # for Spatial GAN:
    n_sample: 10
    npx: 64 # num of pixels width/height of images in X

more_niter:
    <<: *default_params
    batchSize: 1
    niter: 100

texture_syn:
    <<: *default_params
    beta1: 0.1
    lr: 0.0005
    niter: 6400

archpc:
    <<: *default_params
    dataroot: '/data/adam/dataset/plants/green/'
    imageSize: 256
    n_sample: 240
    batchSize: 10
    beta1: 0.1
    lr: 0.0005
    niter: 100
